name: Test pylint

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-pylint-with-astroid-sha:
    uses: emmanuel-ferdman/pylint/.github/workflows/tests.yaml@main
    with:
      repository: emmanuel-ferdman/pylint
      astroid_sha: ${{ github.sha }}
